export enum InputSystemEvents {
  INPUT_DRAG_START = 'INPUT_DRAG_START',
  INPUT_DRAG_UPDATE = 'INPUT_DRAG_UPDATE',
  INPUT_DRAG_END = 'INPUT_DRAG_END',
  INPUT_MOUSE_MOVE = 'INPUT_MOUSE_MOVE',
  INPUT_WHEEL_SCROLL = 'INPUT_WHEEL_SCROLL',
  INPUT_SHORTCUT_ARROW = 'INPUT_SHORTCUT_ARROW',
  INPUT_SHORTCUT_UNDOREDO = 'INPUT_SHORTCUT_UNDOREDO',
  INPUT_SHORTCUT_ZOOM_PRESET = 'INPUT_SHORTCUT_ZOOM_PRESET',
  INPUT_SHORTCUT_SWITCH_PRIMARY_TOOL = 'INPUT_SHORTCUT_SWITCH_PRIMARY_TOOL'
}
